project:
  type: website

website:
  title: "quarto"
  navbar:
    left:
      - text: Survey
        menu: 
          - text: "2015"
            file: notebooks/2015/index.qmd
          - text: "2023"
            file: notebooks/2023/index.qmd

  sidebar:
    - title: "2023"
      style: "docked"
      search: true
      contents:
        - notebooks/2023/index.qmd
        - section: "Demographics"
          contents:
            - notebooks/2023/demographics/age.ipynb

execute:
  freeze: auto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



