project:
  type: website

website:
  title: "quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Demographics"
        contents:
          - age.ipynb


execute:
  freeze: auto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



