project:
  type: website

website:
  title: "quarto"


  sidebar:
      style: "docked"
      search: true
      contents:
          - section: "2023 Onboard Survey"
            contents:
            - notebooks/2023/demographics/age.ipynb
          - section: "2015 Onboard Survey"

execute:
  freeze: auto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



